apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-shmw
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-shmw@sha256:2d05e0ee72b9b78528ce01411c576b3461b2e8b745bab444d33817da90b53493
        name: my-nodejs
        resources: {}
status: {}
